// Code generated by Begonia. DO NOT EDIT.
// versions:
// 	Begonia v1.0.2
// begonia call entity file

package call

type Msg struct {
	ServerName string            `json:&#34;server_name&#34;` // 服务名
	Level      int               `json:&#34;level&#34;`       // 日志等级
	Fields     map[string]string `json:&#34;log_msg&#34;`     // 日志信息
	Time       int64             `json:&#34;time&#34;`        // 时间
	Callers    []string          `json:&#34;callers&#34;`     // 路径
}
