// Code generated by Begonia. DO NOT EDIT.
// versions:
// 	Begonia v1.0.2
// source: begonialog\begonialog.go
// begonia client file

package logger

import (
	"github.com/MashiroC/begonia/app"
	appClient "github.com/MashiroC/begonia/app/client"
	"github.com/MashiroC/begonia/app/coding"
)

var (
	CenterLogServiceService appClient.Service

	_CenterLogServiceServiceRegisterLogService appClient.RemoteFunSync

	_CenterLogServiceServiceRegisterLogServiceInSchema = `
{
			"namespace":"begonia.func.RegisterLogService",
			"type":"record",
			"name":"In",
			"fields":[
				{"name":"F1","type":"string","alias":"name"}

			]
		}`
	_CenterLogServiceServiceRegisterLogServiceOutSchema = `
{
			"namespace":"begonia.func.RegisterLogService",
			"type":"record",
			"name":"Out",
			"fields":[
				
			]
		}`
	_CenterLogServiceServiceRegisterLogServiceInCoder  coding.Coder
	_CenterLogServiceServiceRegisterLogServiceOutCoder coding.Coder

	_CenterLogServiceServiceWrite appClient.RemoteFunSync

	_CenterLogServiceServiceWriteInSchema = `
{
			"namespace":"begonia.func.Write",
			"type":"record",
			"name":"In",
			"fields":[
				{"name":"F1","type":"string","alias":"name"}
,{"name":"F2","type":"bytes","alias":"msg"}

			]
		}`
	_CenterLogServiceServiceWriteOutSchema = `
{
			"namespace":"begonia.func.Write",
			"type":"record",
			"name":"Out",
			"fields":[
				{"name":"F1","type":"string"}

			]
		}`
	_CenterLogServiceServiceWriteInCoder  coding.Coder
	_CenterLogServiceServiceWriteOutCoder coding.Coder

	_CenterLogServiceServiceGetLog appClient.RemoteFunSync

	_CenterLogServiceServiceGetLogInSchema = `
{
			"namespace":"begonia.func.GetLog",
			"type":"record",
			"name":"In",
			"fields":[
				{"name":"F1","type":"string","alias":"name"}

			]
		}`
	_CenterLogServiceServiceGetLogOutSchema = `
{
			"namespace":"begonia.func.GetLog",
			"type":"record",
			"name":"Out",
			"fields":[
				{"name":"F1","type":"bytes"}

			]
		}`
	_CenterLogServiceServiceGetLogInCoder  coding.Coder
	_CenterLogServiceServiceGetLogOutCoder coding.Coder
)

type _CenterLogServiceServiceRegisterLogServiceIn struct {
	F1 string
}

type _CenterLogServiceServiceRegisterLogServiceOut struct {
}

type _CenterLogServiceServiceWriteIn struct {
	F1 string
	F2 []byte
}

type _CenterLogServiceServiceWriteOut struct {
	F1 string
}

type _CenterLogServiceServiceGetLogIn struct {
	F1 string
}

type _CenterLogServiceServiceGetLogOut struct {
	F1 []byte
}

func init() {
	app.ServiceAppMode = app.Ast
	var err error
	_CenterLogServiceServiceRegisterLogServiceInCoder, err = coding.NewAvro(_CenterLogServiceServiceRegisterLogServiceInSchema)
	if err != nil {
		panic(err)
	}
	_CenterLogServiceServiceRegisterLogServiceOutCoder, err = coding.NewAvro(_CenterLogServiceServiceRegisterLogServiceOutSchema)
	if err != nil {
		panic(err)
	}

	_CenterLogServiceServiceWriteInCoder, err = coding.NewAvro(_CenterLogServiceServiceWriteInSchema)
	if err != nil {
		panic(err)
	}
	_CenterLogServiceServiceWriteOutCoder, err = coding.NewAvro(_CenterLogServiceServiceWriteOutSchema)
	if err != nil {
		panic(err)
	}

	_CenterLogServiceServiceGetLogInCoder, err = coding.NewAvro(_CenterLogServiceServiceGetLogInSchema)
	if err != nil {
		panic(err)
	}
	_CenterLogServiceServiceGetLogOutCoder, err = coding.NewAvro(_CenterLogServiceServiceGetLogOutSchema)
	if err != nil {
		panic(err)
	}

}
