package main

var baseClientTmplStr = `// Code generated by Begonia. DO NOT EDIT.
// versions:
// 	Begonia v1.0.2
// begonia base client file

package call

import (
	"github.com/MashiroC/begonia"
)

var BegoniaCli begonia.Client = begonia.NewClientWithAst()
`

var entityTmplStr = `// Code generated by Begonia. DO NOT EDIT.
// versions:
// 	Begonia v1.0.2
// begonia call entity file

package call

import (
	"github.com/MashiroC/begonia"
)

{{range .objs}}
	{{.}}
{{end}}
`
